### ISSUE TITLE
Authority Key Identifier not possible on self-signed certificates

### ISSUE THREAD

**Issue by M0urban** [est31/rcgen#105]
The documentation for CertificatesParams mention for use_authority_key_identifier_extension:

> If true (and not self-signed)

As a reason for the self-signed restriction, the  [source code](https://docs.rs/rcgen/0.10.0/src/rcgen/lib.rs.html#827-834) cites a section from RFC 5280:

> The keyIdentifier field of the authorityKeyIdentifier extension MUST
   be included in all certificates generated by conforming CAs to
   facilitate certification path construction.  There is one exception;
   where a CA distributes its public key in the form of a "self-signed"
   certificate, the authority key identifier MAY be omitted.

But to my understanding this means the omission of the extension is optional and not that it has to be omitted.

Therefore the exception for self-signed certificates should be removed.

**Comment by est31** [comment]
Good point, PRs are welcome.
