### ISSUE TITLE
Feature Request: CRL generation

### ISSUE THREAD

**Issue by Alvenix** [est31/rcgen#109]
Is this feature desirable or is it outside the scope of the crate? I find generating CRLs missing from the rust ecosystem except using openssl bindings. If it is part of the scope, is it okay if I try to make a pull request?

**Comment by est31** [comment]
It's not in the scope of the crate, as this crate is mostly about certificates themselves. The scope can be changed though, I'm open to have my mind changed about this. What do you think synergies are in having this in this crate?

**Comment by mdean75** [comment]
I too, would love to see CRLs supported in this crate.  I have used rcgen to create certificates for testing NGINX and mTLS enablement.  It has allowed my team to develop our solution much quicker than if we had to wait for other teams that manage the actual certificates to deliver a certificate for testing.  We are now moving to implementing CRLs and again will need to generate a test CRL or wait until other teams have completed their work.  

Especially when working with mTLS, we really do need the ability to generate CRLs that are signed by the same cert.  For now I will have to go back to Go which already has the  required support for generating CRLs.

**Comment by est31** [comment]
@mdean75 for reference, which go library you are using for generating CRLs?

**Comment by mdean75** [comment]
x509.CreateRevocationList for creating the CRL byte slice and then pem.Encode to create the pem file.

**Comment by est31** [comment]
Hmmm RFC 5280 specifies both certificates *and* CRLs, which might provide an argument for why rcgen should create CRLs too.

**Comment by cpu** [comment]
I'd like to chime in with my support for `rcgen` getting this feature. I've put a PR up for review/discussion that implements support: https://github.com/est31/rcgen/pull/128

I've recently landed support for working with CRLs to the [Rustls fork of webpki](https://github.com/rustls/webpki). In the coming days/weeks we'll be building on that work to enable using CRLs with Rustls for client certificate revocation checking. This feature has significant demand for mTLS deployments that require a method of revoking a client certificate post-issuance (e.g. if an employee leaves the company, or a service is turned down). 

It would be really nice to have a pure-rust way to generate CRLs for this use case and `rcgen` fits the bill (Thanks for providing this crate!). If rcgen doesn't implement this feature I believe most users will be left reaching for openssl-rs :'( 

> Hmmm RFC 5280 specifies both certificates and CRLs, which might provide an argument for why rcgen should create CRLs too.

I agree :-) The structure of CRLs closely follows X509 certificates. The diff required to implement CRL support is (in my opinion) not very large.

**Comment by est31** [comment]
> The structure of CRLs closely follows X509 certificates. The diff required to implement CRL support is (in my opinion) not very large.

Those are further good points: there is synergies in having one library to generate both. Thanks for filing #128, I think we can add it if it's a small diff as that PR.
