### ISSUE TITLE
Correct way to generate Root CA, Server and Client certificates

### ISSUE THREAD

**Issue by brsnik** [est31/rcgen#111]
The certificates I generate with my code below are not working correctly with a Mutual TLS implementation of gRPC using Tonic. 

Am guessing something is not correctly setup as it's not working. And I've not been able to figure it out.

The error I'm getting from Tonic is `invalid peer certificate contents: invalid peer certificate: MissingOrMalformedExtensions`

This is how I generate the root:
```
    let mut params = CertificateParams::default();
    
    params.alg = &PKCS_ECDSA_P384_SHA384; 
    params.key_pair = Some(KeyPair::generate(&PKCS_ECDSA_P384_SHA384)?);
    params.key_identifier_method = KeyIdMethod::Sha384;
    
    let mut dn = DistinguishedName::new(); 
    dn.push( 
        DnType::CommonName, 
        DnValue::PrintableString("Test Root CA ECC".to_string()), 
    ); 
    params.distinguished_name = dn;
    params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
    
    params.not_before = OffsetDateTime::now_utc(); 
    params.not_after = OffsetDateTime::now_utc() + Duration::days(365 * 10);
    
    params.key_usages = vec![
        KeyUsagePurpose::KeyCertSign, 
        KeyUsagePurpose::CrlSign
    ];
    let cert = Certificate::from_params(params)?;
    
    let cert_pem = cert.serialize_pem(); 
    let mut cert_file = fs::File::create("cert_root.pem")?;
    cert_file.write_all(cert_pem.unwrap().as_bytes())?;
    
    let private_key_pem = cert.serialize_private_key_pem(); 
    let mut private_key_file = fs::File::create("cert_root.key")?;
    private_key_file.write_all(private_key_pem.as_bytes())?;
```
The server:
```
    let mut params = CertificateParams::default();
    
    params.alg = &PKCS_ECDSA_P384_SHA384;
    params.key_pair = Some(KeyPair::generate(&PKCS_ECDSA_P384_SHA384).unwrap()); 
    params.key_identifier_method = KeyIdMethod::Sha384;
    
    let mut dn = DistinguishedName::new();
    dn.push( 
        DnType::CommonName, 
        DnValue::PrintableString("r.u.local".to_string()),
    );
    params.distinguished_name = dn;
    
    params.subject_alt_names = vec![ 
        SanType::DnsName("localhost".to_string()),        
        SanType::IpAddress(
            std::net::IpAddr::V4(
                std::net::Ipv4Addr::new(127, 0, 0, 1)
            )
        ),
        SanType::IpAddress(
            std::net::IpAddr::V6(
                std::net::Ipv6Addr::new( 0, 0, 0, 0, 0, 0, 0, 1, )
            )
        ),
    ];
    
    params.not_before = OffsetDateTime::now_utc();
    params.not_after = OffsetDateTime::now_utc() + Duration::days(365 * 1);
    
    let cert = Certificate::from_params(params)?; 
    let cert_signed = cert.serialize_pem_with_signer(&root_cert)?;
```
And the client:
```
    let mut params = CertificateParams::default();
    
    params.alg = &PKCS_ECDSA_P384_SHA384;
    params.key_pair = Some(KeyPair::generate(&PKCS_ECDSA_P384_SHA384).unwrap());
    params.key_identifier_method = KeyIdMethod::Sha384;
    
    let mut dn = DistinguishedName::new();
    params.distinguished_name = dn;
    
    params.not_before = OffsetDateTime::now_utc();
    params.not_after = OffsetDateTime::now_utc() + Duration::days(365 * 1);
    
    let cert = Certificate::from_params(params)?;

    let cert_signed = cert.serialize_pem_with_signer(&root_cert)?;
```
Do I need to use the `ExtendedKeyUsagePurpose` and set `ClientAuth` & `ServerAuth`?

Am I missing something else?

**Comment by est31** [comment]
You seem to be using rustls. I think the issue might be webpki not supporting ip addresses? Have you tried using rustls from master, they have forked webpki to add the feature.

**Comment by grimvoodoo** [comment]
> 

Hi,
This is exactly what I am trying to do, can you explain with a bit more detail how you got it working?

At the moment I can generate a CA and I can sign another cert with it, but something is still not right as it doesnt accept it when I try to deploy it in a test pod. This is the code I have written so far (I did grab some from your example, like the date as I previously left that on default.

`#![allow(clippy::complexity, clippy::style, clippy::pedantic)]
extern crate openssl;
extern crate pem;
extern crate rcgen;
extern crate time;

use rcgen::{
    Certificate, CertificateParams, DistinguishedName, IsCa, KeyPair, KeyUsagePurpose, SanType,
};
use std::fs;

fn main() {
    let ca = create_ca_cert();
    println!("{}", ca.serialize_pem().unwrap());
    let grimmy = signed_cert(&ca, String::from("foobar.co.uk"));
    println!("{}", grimmy.serialize_pem().unwrap());
}

fn create_ca_cert() -> Certificate {
    let key_pair = KeyPair::generate(&rcgen::PKCS_ECDSA_P256_SHA256).unwrap();

    let mut dn = DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, "rootca");

    let mut params = CertificateParams::default();
    params.is_ca = IsCa::Ca(rcgen::BasicConstraints::Unconstrained);
    params.distinguished_name = dn;
    params.key_pair = Some(key_pair);
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = time::OffsetDateTime::now_utc() + time::Duration::days(365 * 20);

    params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];

    let cert = Certificate::from_params(params).unwrap();

    let cert_pem = cert.serialize_pem().unwrap();

    std::fs::create_dir_all("certs/").unwrap();
    fs::write("certs/rootca.pem", &cert_pem.as_bytes()).unwrap();
    fs::write(
        "certs/rootca_key.pem",
        &cert.serialize_private_key_pem().as_bytes(),
    )
    .unwrap();
    cert
}

fn signed_cert(ca_cert: &Certificate, dn_name: String) -> Certificate {
    let key_pair = KeyPair::generate(&rcgen::PKCS_ECDSA_P256_SHA256).unwrap();

    let mut dn = DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, dn_name);

    let mut params = CertificateParams::default();
    params.distinguished_name = dn;
    params.key_pair = Some(key_pair);
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = time::OffsetDateTime::now_utc() + time::Duration::days(365 * 20);

    params.subject_alt_names = vec![
        SanType::DnsName(String::from("localhost")),
        SanType::IpAddress(std::net::IpAddr::V4(std::net::Ipv4Addr::new(127, 0, 0, 1))),
        SanType::IpAddress(std::net::IpAddr::V6(std::net::Ipv6Addr::new(
            0, 0, 0, 0, 0, 0, 0, 1,
        ))),
    ];

    let cert = Certificate::from_params(params).unwrap();
    let cert_signed = cert.serialize_pem_with_signer(ca_cert).unwrap();

    std::fs::create_dir_all("certs/").unwrap();
    fs::write("certs/cert.pem", &cert_signed.as_bytes()).unwrap();
    fs::write(
        "certs/key.pem",
        &cert.serialize_private_key_pem().as_bytes(),
    )
    .unwrap();

    cert
}`

**Comment by brsnik** [comment]
@grimvoodoo When you say the CA doesn't trust it what do you mean? Are you getting some kind of an error? Could it be that the CA is not whitelisted in your OS?

**Comment by grimvoodoo** [comment]
> @grimvoodoo When you say the CA doesn't trust it what do you mean? Are you getting some kind of an error? Could it be that the CA is not whitelisted in your OS?

Ah, it was my own fault. I forgot to add the DistiguisedName to the Subject_alt_names. With that done its working great :+1:

**Comment by grimvoodoo** [comment]
Hi, I am trying to load in a CA from a pem file and struggling to convert it to a Certificate type. It looks like you have managed it as you are referencing &root_cert here, How did you import the CA from a file?

Ive been playing with a few different methods and I can get it into a Vec<u8> or a PublicKey but cant get it back into a Certificate type.

> let cert_signed = cert.serialize_pem_with_signer(&root_cert)?;

**Comment by est31** [comment]
@grimvoodoo you use `CertificateParams::from_ca_cert_pem(...)` and then you do `Certificate::from_params(...)`.

**Comment by grimvoodoo** [comment]
Hi, sorry to keep being a pain about this, I have been attacking this from different angles for a few days now but I cant get it working. I feel like I am almost there with this current block but I get a `CouldNotParseCertificate` error, can you see what the problem is with this block?

`
fn signed_cert_with_ca(ca_cert_path: String, dn_name: String) {
    // Read the CA file as a String type
    let ca_file = read_to_string(&ca_cert_path).unwrap();

    // Generate new KeyPair for the new Certificate
    let key_pair = KeyPair::generate(&rcgen::PKCS_ECDSA_P256_SHA256).unwrap();

    // set the DistinguisedName
    let mut dn = DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, dn_name.clone());

    // Create the params using the `from_ca_cert_pem` this is where it crashes with a 'CouldNotParseCertificate' error
    let mut params = CertificateParams::from_ca_cert_pem(&ca_file, key_pair).unwrap();

    params.distinguished_name = dn;
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = time::OffsetDateTime::now_utc() + time::Duration::days(365 * 20);

    params.subject_alt_names = vec![
        SanType::DnsName(dn_name.clone()),
        SanType::DnsName(String::from("localhost")),
        SanType::IpAddress(std::net::IpAddr::V4(std::net::Ipv4Addr::new(127, 0, 0, 1))),
        SanType::IpAddress(std::net::IpAddr::V6(std::net::Ipv6Addr::new(
            0, 0, 0, 0, 0, 0, 0, 1,
        ))),
    ];

    let cert = Certificate::from_params(params).unwrap();
    let path = format!("certs/{dn_name}/");
    let cert_path = format!("certs/{dn_name}/{dn_name}.pem");
    let key_path = format!("certs/{dn_name}/{dn_name}.key");

    std::fs::create_dir_all(path).unwrap();
    fs::write(cert_path, &cert.serialize_pem().unwrap()).unwrap();
    fs::write(key_path, &cert.serialize_private_key_pem().as_bytes()).unwrap();
}
`

**Comment by brsnik** [comment]
@grimvoodoo Where exactly is your problem? When you read the root from file or? The code I posted above is functional, you just need to add ExtendedKeyUsagePurpose for the Client and Server respectively.

**Comment by grimvoodoo** [comment]
The issue is reading the CA file. in this function for example I pass in the location of the CA file and the domain name itselt, so in this case it woult be something like `signed_cert_with_ca("certs/rootca.pem", "foobar.com")`:

```
fn signed_cert_with_ca(ca_cert_path: String, dn_name: String) {
    let ca_file = read_to_string(&ca_cert_path).unwrap();
    let key_pair = KeyPair::generate(&rcgen::PKCS_ECDSA_P256_SHA256).unwrap();

    let mut dn = DistinguishedName::new();
    dn.push(rcgen::DnType::CommonName, dn_name.clone());

    let mut params = CertificateParams::from_ca_cert_pem(&ca_file, key_pair).unwrap();

    params.distinguished_name = dn;
    params.not_before = time::OffsetDateTime::now_utc();
    params.not_after = time::OffsetDateTime::now_utc() + time::Duration::days(365 * 20);

    params.subject_alt_names = vec![
        SanType::DnsName(dn_name.clone()),
        SanType::DnsName(String::from("localhost")),
        SanType::IpAddress(std::net::IpAddr::V4(std::net::Ipv4Addr::new(127, 0, 0, 1))),
        SanType::IpAddress(std::net::IpAddr::V6(std::net::Ipv6Addr::new(
            0, 0, 0, 0, 0, 0, 0, 1,
        ))),
    ];

    let cert = Certificate::from_params(params).unwrap();

    let path = format!("certs/{dn_name}/");
    let cert_path = format!("certs/{dn_name}/{dn_name}.pem");
    let key_path = format!("certs/{dn_name}/{dn_name}.key");

    std::fs::create_dir_all(path).unwrap();
    fs::write(cert_path, &cert.serialize_pem().unwrap()).unwrap();
    fs::write(key_path, &cert.serialize_private_key_pem().as_bytes()).unwrap();
}
```

It fails on the `let mut params = CertificateParams::from_ca_cert_pem(&ca_file, key_pair).unwrap();` with:
`'Err' value: CouldNotParseCertificate`

From your code it seems you are passing in the `&root_cert` but I cant see what that variable is and how its generated. I am curious if this is just the cert generated by the create CA step or if you are reading it from a file somewhere else and passing in the result?

`let cert_signed = cert.serialize_pem_with_signer(&root_cert)?;`

**Comment by brsnik** [comment]
You can see above how I generate the root.

And then to sign the other certs I read it from file like so:
```
pub fn read_root_cert() -> Result<Certificate, Box<dyn std::error::Error>> {
    // Open the PEM file containing both the certificate and private key
    let pem_cert_file = File::open("_cert_root.pem")?;
    let mut pem_cert_reader = BufReader::new(pem_cert_file);

    let mut cert_string = String::new();
    pem_cert_reader.read_to_string(&mut cert_string)?;

    let pem_key_file = File::open("_cert_root.key")?;
    let mut pem_key_reader = BufReader::new(pem_key_file);

    let mut key_pair_sting = String::new();
    pem_key_reader.read_to_string(&mut key_pair_sting)?;

    let key_pair = KeyPair::from_pem(key_pair_sting.as_str())?;

    // Parse the PEM file and create a new CertificateParams object
    let ca_cert_params = CertificateParams::from_ca_cert_pem(cert_string.as_str(), key_pair)?;

    // Create a new certificate using the CertificateParams object
    let ca_cert = Certificate::from_params(ca_cert_params)?;

    //let ca_sign = CertificateSigningRequest::from_per(ca_cert.serialize_pem_with_signer(ca))?;

    Ok(ca_cert)
}
```

This function can be greatly simplified.

Does this help?

**Comment by grimvoodoo** [comment]
perfect, that was the bit I was missing. Its now all working correctly :+1:

**Comment by brsnik** [comment]
Glad it helped :)
