### ISSUE TITLE
Pem defaults to CRLF, and there is no way to configure it through rcgen

### ISSUE THREAD

**Issue by frjonsen** [est31/rcgen#115]
When serializing to PEM, rcgen [simply calls pem::encode](https://github.com/est31/rcgen/blob/master/src/lib.rs#L1612).

The `pem` package [defaults to using CRLF](https://github.com/jcreekmore/pem-rs/blob/master/src/lib.rs#L463). To use LF, one must instead call the `encode_config`, but as far as I can tell there's no way of doing this through rcgen. Instead I have pull in the `pem` crate manually and duplicate what `serialize_pem` does. Admittedly the workaround is pretty minor, but most of all it's unexpected to get a PEM with CRLF linebreaks when working on Linux.

Would it perhaps be possible to change the serialize_pem functions and the other variants of the function to attempt to determine linebreaks from the current OS, or would that be considered too breaking?

**Comment by est31** [comment]
A simpler workaround would be to use str::replace I guess but your approach also works.

But this is a valid bug nontheless. Thanks for notifying! I've thought that the pem crate emitted the endings based on the current platform, but I guess I was wrong. Ideally this would be the behaviour of rcgen: CRLF on windows, LF everywhere else. PRs welcome!

**Comment by est31** [comment]
#118 is merged now
