### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dignifiedquire** [est31/rcgen#124]
Any chance a new release with the updated dependencies could be cut? Thanks!

**Comment by est31** [comment]
As said in https://github.com/est31/rcgen/issues/121#issuecomment-1557035445 , I was waiting for #118. I think given that the issue that prevents merging of #118 is still not resolved, I will just do a release anyways or alternatively, i will merge #118 with a different windows CI.

**Comment by est31** [comment]
0.11.0 is out, enjoy.

**Comment by dignifiedquire** [comment]
thank you!
