### ISSUE TITLE
Add Botan CRL parsing test coverage

### ISSUE THREAD

**Issue by cpu** [est31/rcgen#132]
In https://github.com/est31/rcgen/pull/128 I identified that it wasn't possible to add CRL parsing test coverage w/ [botan-rs](https://github.com/randombit/botan-rs) at the time of writing because the upstream project wasn't exposing the required  `X509_CRL` type from the underlying C++ library.

That's since been fixed: https://github.com/randombit/botan-rs/issues/95 :tada: It should now be possible to write some simple unit tests that ensure the CRLs generated by `rcgen` can be parsed by `botan-rs`.

Since the `botan-rs` project hasn't cut a release with this functionality yet it will require a Cargo patch to use the unreleased code from git. Probably best to add some initial tests as a draft PR to demonstrate the API changes are sufficient for testing and then hold merge on a botan-rs release to avoid the Cargo patch.

**Comment by est31** [comment]
@cpu sounds like a reasonable approach to me!
