### ISSUE TITLE
Extend public key pair interface

### ISSUE THREAD

**Issue by nthuemmel** [est31/rcgen#15]
It would be great to have additional methods to interact with a specified or generated keypair.
Right now, I am missing two features:

* Exporting the public key, for both `KeyPair` and `Certificate`, in DER format (example: `serialize_public_key_der(&self) -> Vec<u8>`)
* Having the option to check `KeyPair` compatibility with a given algorithm manually (making `KeyPair::is_compatible(...)` public should do the trick)

**Comment by est31** [comment]
I've seen @fzgregor push some commits so it's his.

**Comment by fzgregor** [comment]
Public Key interface implemented in https://github.com/est31/rcgen/pull/20/commits/4700d6a7bcc509b96198cd23004ae22da75af99c

**Comment by est31** [comment]
Fixed by #20 / 620b1b4f65ed259c9623b557209f956fa7e143fe
