### ISSUE TITLE
KeyPair::is_compatible yields wrong result for different ECDSA key types

### ISSUE THREAD

**Issue by nthuemmel** [est31/rcgen#18]
`KeyPair::is_compatible()` yields true when:

* The Keypair is of type P384 and the given alg is `PKCS_ECDSA_P256_SHA256`
* The Keypair is of type P256 and the given alg is `PKCS_ECDSA_P384_SHA384`

This has the consequence that when `CertificateParams` have such a combination of algorithm & `KeyPair` a `Certificate` will be generated without error, but will have a mismatch between public key type and public key data, rendering it ill-formed.

**Comment by est31** [comment]
Fixed by #20 / 620b1b4f65ed259c9623b557209f956fa7e143fe
