### ISSUE TITLE
Allow omitting default extensions

### ISSUE THREAD

**Issue by DemiMarie-parity** [est31/rcgen#29]
libp2p doesn’t need them, and they bloat the handshake.

**Comment by est31** [comment]
The only extension that can't be turned off from the API is the Subject Alternative Name extension. We could omit it when some param is passed to omit it. What do you think?

**Comment by DemiMarie-parity** [comment]
That works for my purposes.

**Comment by est31** [comment]
Alright, fixed it in 6cb091ad20f0b7f47d0becf7f860a29f3408b834 . A separate param hasn't been needed after all because the extension is not allowed to be empty. So if it would have been empty, we just don't write it. Please write if you need a new crates.io release.

**Comment by DemiMarie-parity** [comment]
@est31 A new release would be great, thanks!

**Comment by est31** [comment]
@DemiMarie-parity it's since happened. Check out the 0.8.1 release.
