### ISSUE TITLE
Question Generating Certificate when we have key?

### ISSUE THREAD

**Issue by shirshak55** [est31/rcgen#36]
I  want to generate self signed certificate for mitm proxy. I used openssl to generate key

```
openssl genrsa -out cert.key 2048
openssl req -new -x509 -key cert.key -out cert.crt
```

But as it is mitm proxy I need to adjust certificate subject line ON feild according to request. If request comes for xyz.com i need to change ON=xyz.com and if it comes for jsonip.com I need to change certificate subject to `ON=jsonip.com` so I wont see tls error.

How do generate x509 key in such case where i just need to change ON and nothing else?

I  basically wanted to create root cert  and key using open ssl  command add it to trusted root certificate . And using rcgen wanted to generate x509 certificate with the change of subject line having `OU=xyz.com`.

I hope there is easy way to accomplish this with rcgen.
Thanks.

**Comment by est31** [comment]
Yeah it's doable. You call `CertificateParams::from_ca_cert_pem` to get the params of the CA cert, then you use `Certificate::from_params` to build it. Then you build separate CertificateParams with the desired domain names, and sign them with the CA cert using `serialize_pem_with_signer`. You'll need to enable the `pem` and `x509-parser` features of the crate.

**Comment by shirshak55** [comment]
thanks

**Comment by shirshak55** [comment]
@est31  can u let me know how to make keypair.
```
 let mut cert_file = File::open("/Users/quantum/Desktop/code/mitm/cert.pem").unwrap();
    let mut cert_buf = String::new();
    cert_file.read_to_string(&mut cert_buf).unwrap();

  let key_pair = rcgen::KeyPair::from_pem(&cert_buf[..]);
    dbg!(key_pair);
```

I tried that but it always give me 
```
[src/cert.rs:22] key_pair = Err(
    CouldNotParseKeyPair,
)
```

I generated key pair with this 
```
openssl genrsa -out cert.key 2048
openssl req -new -x509 -key cert.key -out cert.crt
cat cert.key cert.crt > cert.pem
```

I have been trying for 12 hour without success :(.

**Comment by est31** [comment]
@shirshak55 maybe you should load two files, one with the certificate, one with the certificate's key?

**Comment by shirshak55** [comment]
@est31  hmm i tried with all three file

```
cert.key
cert.crt
cert.pem
```

Pem parser will parse it but its failing in try into.

```
Ok(private_key_der.try_into()?)
```

**Comment by est31** [comment]
Oh yeah the key generation command doesn't create keys that ring can read. You have to use this command:

```
openssl genpkey -algorithm RSA \
 -pkeyopt rsa_keygen_bits:2048 \
 -pkeyopt rsa_keygen_pubexp:65537 | \
 openssl pkcs8 -topk8 -nocrypt -outform pem
```

**Comment by est31** [comment]
See also: https://docs.rs/ring/0.16.15/ring/signature/struct.RsaKeyPair.html#method.from_pkcs8

**Comment by shirshak55** [comment]
@est31 thank you so much the key generated by command worked :)
