### ISSUE TITLE
[Question] modifying distinguished_name

### ISSUE THREAD

**Issue by shirshak55** [est31/rcgen#37]
I was able to create `CertificateParam` from existing certificate. But I only want to change OU field of certificate.

What i found is internally it is stored in  CerficateParam's `distinguished_name` field. 

The unfortunate situation is `DistinguishedName` has two field which are not public . And `DistinguishedName` only provides new get push and iter which doesn't give ability to modify the internal value inside hashmap?

Here was my initial thought . 

```
 let mut param =
        CertificateParams::from_ca_cert_pem(&cert_buf[..], key_pair).expect("Invalid pem key");

       if let Some(x) = param.distinguished_name.entries.get_mut(rcgen::DnType::CustomDnType(u64::from_ne_bytes(b"OU"))) {
         *x = "yahoo.com"; // yahoo.com is what i want to set of course dynamically
     }
```

But unfortunately param.distinguished_name.entries is private :(

Let me know if i am doing something wrong?

Thanks :)

**Comment by est31** [comment]
First, the OU is not specified that way. You have to use the set of numbers as defined by `id-at-organizationalUnitName` in RFC 5280. Second, it seems you want to set the domain name the certificate is valid for, that's not really done by setting the OU but by the `subject_alt_names` field.

If you really want to set a single field in the distinguished name then you can always iter over param.distinguished_name, and edit the field you want to edit on the fly, while building the new distinguished name using push.

**Comment by shirshak55** [comment]
Sorry i wanted to set CN (Common Name) field but don't know why i said OU field. To be honest i did changed subject lines initially.

What subject alt does is it changed `Subject Alternative Names` which didn't worked out.  Is there 

https://github.com/shirshak55/mitm/blob/master/src/cert.rs#L21

So for set a single field in distinguished name especially CommonName should i reconstruct everything? I thought it would be better if we can use the key `CommonName` inside hash map and edit it on fly? 

Thanks :)

**Comment by shirshak55** [comment]
after checking internals i found we can directly use push as pushing `distinguished_name` means  updating the hashmap :)

Thanks a lot :)

**Comment by est31** [comment]
> after checking internals i found we can directly use push as pushing distinguished_name means updating the hashmap :)

Oh indeed. This should be pointed out in the docs. Thanks to you I'm finding tons of documentation issues :).

**Comment by est31** [comment]
Alright I've made two commits: 6d62e7bb2e99f9a42eed2598281bdd9908715b91 to add some docs and 263c219f60be5fd3a518d67eeb888018fbf1edcf to add a remove function. Now you should have full create/read/update/delete functionality. Only reordering requires an iteration now. Will add it if people show an use case for it.
