### ISSUE TITLE
Info Request[Openssl dependency]

### ISSUE THREAD

**Issue by amitather** [est31/rcgen#38]
What is the dependency of `Openssl` for this lib? Is it just for verification of generated certs ?

**Comment by est31** [comment]
Yeah it's mainly to check that openssl can read the certificates we generate. If you use rcgen as a dependency, openssl is not being downloaded or compiled. Only if you clone rcgen from git and use cargo test or cargo build on it directly it is used. Same goes for webpki.

See this link: https://doc.rust-lang.org/stable/rust-by-example/testing/dev_dependencies.html
