### ISSUE TITLE
Documentation improvement: mention the "x509-parser" feature flag

### ISSUE THREAD

**Issue by jamadazi** [est31/rcgen#39]
I wasted a lot of time trying to figure out that I needed to enable the optional extra "x509-parser" feature flag, in order to use the `CertificateParams::from_ca_cert_{pem,der}` functions, which I found from the API docs on `docs.rs`. This is not mentioned in the documentation or the readme. `docs.rs` API documentation is generated with the feature enabled, giving the impression that the functions are available.

It would be nice if a mention about this is added somewhere relevant.

**Comment by est31** [comment]
Yeah it's standard practice to add such remarks to the rustdoc of behind-feature functionality. PRs welcome!
