### ISSUE TITLE
Botan needlessly disabled on macOS

### ISSUE THREAD

**Issue by randombit** [est31/rcgen#52]
Just an FYI the logic in https://github.com/est31/rcgen/pull/42 is incorrect, Botan supports macOS (aka `x86_64-apple-darwin`) just fine, and has for years. It does not support the old MacOS "Classic" which nobody uses anymore. I think the confusion came about because of the recent rebranding of OS X to macOS, plus the fact that the docs even bothered mentioning Classic, which has been dead for 20 years. I've amended Botan's documentation so the situation is more clear.

**Comment by est31** [comment]
@randombit thanks for opening an issue! I've tried to re-enable botan on mac-os in PR #53 but it causes a CI failure.

```
   = note: ld: library not found for -lstdc++
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you know how it can be fixed?

**Comment by randombit** [comment]
@est31 Interesting - I just added a macOS CI build for the Rust wrapper in https://github.com/randombit/botan-rs/pull/38 and everything worked fine but I see you are using a vendored build and that may make a difference somehow. Possibly on macOS we should be using Clang's `libc++` instead? I'll take a look at this tomorrow.

**Comment by randombit** [comment]
Oh I found out what is going on - our vendored build needs to be able to dynamically link against the system C++ library and that code was written to always use `libstdc++`, which is to first approximation incorrect on anything that is not Linux. I'll have to publish a new release with the fix.

**Comment by est31** [comment]
@randombit thanks for digging up the cause! Please ping me if you make the release!

**Comment by randombit** [comment]
`botan 0.8.1` should resolve the build problem on macOS

**Comment by est31** [comment]
Huh apparently the PR hit an ICE in nightly Rust: https://github.com/rust-lang/rust/issues/83126

... it only happens on mac OS, that's strange.
