### ISSUE TITLE
Ability to generate a certificate from (remote) raw private key

### ISSUE THREAD

**Issue by daxpedda** [est31/rcgen#56]
Currently there is no way to generate a full X.509 certificate from a raw private and public key.
Additionally support for a "remote" raw private key would be amazing too, with remote meaning that no direct access is available, but a callback to signing is.

At the moment my ad-hoc solution is to copy some parts of rcgen.

I would propose to add an `enum` of sorts to `rcgen::CertificateParams::key_pair` that has the ability to take in a `Box` to a trait similar to [`rustls::sign::SigningKey`](https://docs.rs/rustls/0.19.1/rustls/sign/trait.SigningKey.html) and the public key in it's raw form.

Intending to make a PR myself if it's decided that this falls into the scope of rcgen.

My use case:
I'm currently writing a library that enables cross-platform access to the OS certificate vault and store. This includes generation, storage and some level of editing.

The goal is to be able to generate a key pair inside the OS vault and use that for example in rustls. When done that way, there is no access to the private key directly. This works great with rustls because it offers [`SigningKey`](https://docs.rs/rustls/0.19.1/rustls/sign/trait.SigningKey.html), which can call the OS vault signing function to sign a message without direct access to the private key.

The missing part is X.509 certificate generation. All three OS's (Linux, MacOS and Windows) generate only raw keys. Which is a great option for the future: https://github.com/ctz/rustls/issues/423.
But right now and in some other use cases, for example using it on a server with a HSM for example, you need to generate a X.509 certificate from the already generated raw keys in addition to the private key not being directly accessible.

At the moment the usual solution is to use tools or OS API's to generate certificates, it would be great to allow that to be replaced by rcgen.

**Comment by est31** [comment]
Thanks for filing this issue @daxpedda ! I'd welcome a PR that adds support for OS/HSM provided signing functionality. Regarding your suggestion of adding an enum, in fact there is already an enum called `KeyPairKind` which abstracts over different `ring` provided key pairs. I would suggest the following steps for a PR:

* Add a new trait `RemoteKeyPair` containing a signing function as well as a function that returns a `&SignatureAlgorithm`
* add a variant to the `KeyPairKind` enum containing a boxed dyn trait impl of `RemoteKeyPair` and
* add a new constructor `KeyPair::from_remote(Box<dyn RemoteKeyPair>)` that creates a new `KeyPair`. It should set the internal `serialized_der` member to an empty vec
* Make `KeyPair::serialize_der` panic if the vec is empty (and also document that it panics if called with a remote key pair). In future versions of rcgen, we might return an `Option` instead.
* Add a test based on `RemoteKeyPair` that internally uses a vanilla `KeyPair`. It can reside in the webpki.rs test.
