### ISSUE TITLE
Loading CA cert and using for signing doesn't match original certificate

### ISSUE THREAD

**Issue by geeklint** [est31/rcgen#59]
I'm trying to develop a P2P application where clients can register with a server, which will sign their certificates, so that they can later talk to each other without the involvement of the server.

I've been trying to load the CA cert using `CertificateParams::from_ca_cert_pem` and sign the client certs with `Certificate::serialize_der_with_signer`.  However the "issuer" attached to the resulting signed cert doesn't match the original cert (specifically the "subject" is 1 byte different).

I don't really know enough about TLS to figure out why this is happening, so let me know if I can provide any additional details.

My (testing) code looks like this:

```rust
    let ca_key = rcgen::KeyPair::from_der(debug_certs::CA_KEY_PK8).unwrap();
    let params = rcgen::CertificateParams::from_ca_cert_pem(
        debug_certs::CA_CERT,
        ca_key,
    )
    .unwrap();
    let ca_cert = rcgen::Certificate::from_params(params).unwrap();
    let gen_cert = rcgen::generate_simple_self_signed(vec![hostname]).unwrap();
    gen_cert.serialize_der_with_signer(&ca_cert).unwrap();
```

The issuer "subject" lines I get during certificate verification look like this (as byte arrays, note byte index 9)

Certificate "Issuer":
```
[49, 11, 48, 9, 6, 3, 85, 4, 6, 12, 2, 85, 83, 49, 17, 48, 15, 6, 3, 85, 4, 8, 12, 8, 86, 105, 114, 103, 105, 110, 105, 97, 49, 33, 48, 31, 6, 3, 85, 4, 10, 12, 24, 73, 110, 116, 101, 114, 110, 101, 116, 32, 87, 105, 100, 103, 105, 116, 115, 32, 80, 116, 121, 32, 76, 116, 100]
```
Trust Anchor "Subject":
```
[49, 11, 48, 9, 6, 3, 85, 4, 6, 19, 2, 85, 83, 49, 17, 48, 15, 6, 3, 85, 4, 8, 12, 8, 86, 105, 114, 103, 105, 110, 105, 97, 49, 33, 48, 31, 6, 3, 85, 4, 10, 12, 24, 73, 110, 116, 101, 114, 110, 101, 116, 32, 87, 105, 100, 103, 105, 116, 115, 32, 80, 116, 121, 32, 76, 116, 100]
```

[debug-game-cert.pem.txt](https://github.com/est31/rcgen/files/6644906/debug-game-cert.pem.txt)
[example_signed_cert.pem.txt](https://github.com/est31/rcgen/files/6644909/example_signed_cert.pem.txt)

**Comment by est31** [comment]
Hmm yeah apparently the countryName is a `PrintableString` in the (presumably openssl generated) cert while it's an UTF8String in the rcgen generated cert. Ideally one would just extract the entire ASN.1 of the signer key as-is and then dump it out again.

In the meantime, I suggest trying to create a root certificate using rcgen. rcgen will then create an UTF8String in the first place and thus avoid this issue.

**Comment by geeklint** [comment]
> In the meantime, I suggest trying to create a root certificate using rcgen. rcgen will then create an UTF8String in the first place and thus avoid this issue.

This workaround is working for me for now, thanks!
