### ISSUE TITLE
0.8.12 is an API breaking change; Certificate is no longer Send or Sync

### ISSUE THREAD

**Issue by wez** [est31/rcgen#63]
Contrast:
https://docs.rs/rcgen/0.8.11/rcgen/struct.Certificate.html

with:
https://docs.rs/rcgen/0.8.12/rcgen/struct.Certificate.html

I'd suggest yanking 0.8.12 and either restoring Send+Sync in 0.8.13, or instead releasing 0.9.0 with them removed

**Comment by neonphog** [comment]
Ran into this as well, [pinned to 0.8.11](https://github.com/holochain/lair/pull/42) in the intirim.

**Comment by est31** [comment]
Sorry about that. It is because of the remote key pair changes. Adding a trait bound fixes it. I've fixed it on master with 09d0bcc0a8b9fafcd9ab2337500eb72e1579b778 . I'll make a release very soon.

**Comment by est31** [comment]
0.8.12 is yanked and 0.8.13 is out. Please write if there are any more issues.

**Comment by wez** [comment]
Thanks!  It builds for me :)
