### ISSUE TITLE
Add extensionRequest to Serialized Certificate Signing Requests

### ISSUE THREAD

**Issue by ophilli** [est31/rcgen#64]
Currently users of rcgen can set many fields in CertificateParams that will be silently ignored when serializing a CSR.

One example is:
```
use rcgen;

let mut params = CertificateParams::default();

// https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.3
params.key_usages.push(KeyUsagePurpose::DigitalSignature);
params.key_usages.push(KeyUsagePurpose::KeyEncipherment);
params.key_usages.push(KeyUsagePurpose::KeyAgreement);

// ServerAuth may be consistent with DigitalSignature, KeyEncipherment, and KeyAgreement per rfc5280 #4.2.1.12
// https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12
params
    .extended_key_usages
    .push(ExtendedKeyUsagePurpose::ServerAuth);

params.key_pair = Some(KeyPair::from_der(pkcs8_bytes)?);

let certificate = Certificate::from_params(params)?;

certificate.serialize_request_pem()?
```
In this example the `key_usages` and `extended_key_usages` fields will not be present in the serialized CSR.

Per [rfc2985 5.4.2](https://datatracker.ietf.org/doc/html/rfc2985#page-17) the `extensionRequest` attribute type may be used to carry information about certificate extensions the requester wishes to be included in a certificate.

It seems to me that `subject_alt_names`, `key_usages`, `extended_key_usages`, `name_constraints`, `custom_extensions`, and the `use_authority_key_identifier_extension` fields are all valid things to include in the `extensionRequest` attribute. [Currently](https://github.com/est31/rcgen/blob/master/src/lib.rs#L709-L724) it seems like `subject_alt_names` is the only thing that is included.

Would you be open to merging a PR that adds `key_usages`, `extended_key_usages`, `name_constraints`, `custom_extensions`, and the `Authority Key Identifier` extensions to the extension request section during CSR serialization?

**Comment by g2p** [comment]
I was wondering why adding must-staple (as a custom extension) had no effect on the CSR; silently ignored fields are bad.

I'm not sure what would be best for a pull request:
forking CSRParams from CertificateParams, warning or erroring when parameters have been set and write_request is ignoring them, adding everything that can be supported to CSR serialization?  I might go with 2 + 3, but they will need to be maintained when fields are added to CertificateParams.
