### ISSUE TITLE
RcgenError variants for "third-party" failures in RemoteKeyPair

### ISSUE THREAD

**Issue by paulhowardarm** [est31/rcgen#67]
I am currently investigating this crate for potential use within the [Parsec project](https://github.com/parallaxsecond/parsec), since it provides the ideal facilities for creating certs and CSRs from a private key that is managed in hardware. The `RemoteKeyPair` trait provides a nice extension point where I can call out to key functions that are implemented in Parsec (which in turn can then be back-ended into a variety of TPMs, HSMs or secure elements).

One small interface wrinkle is in the error handling. The `RemoteKeyPair::sign()` function is contracted to return `RcgenError` on a failure. But this is an enum with a fixed set of variants, and none of the existing variants is directly applicable if the signing function fails in a third-party component. It would be good to have a `RcgenError::RemoteKeyError` or something similar to flag when the remote implementation has encountered an error that is not explicitly modelled in the existing variants.

**Comment by est31** [comment]
That's a good point. PRs welcome!

**Comment by paulhowardarm** [comment]
Thanks for the feedback - I will aim to contribute this since it's a small change. I just need to go through a bit of process with my employer to clear me for contribution.

**Comment by est31** [comment]
Sure. If it's too much to bother please tell, I can implement it myself if needed. I wonder whether `RemoteKeyError` should have a payload, and what that payload should be.

**Comment by paulhowardarm** [comment]
Hmmm, a string message maybe? I'm not sure if that's good style for Rust errors, though. I think for now it would be good to just have an enum member to represent "something went wrong in code outside of this library", which is probably all you can do with no information about how the remote key was implemented.

**Comment by est31** [comment]
Yeah a string is not really good style. I'll check if an opaque payload is doable. If not, I'll just not add one, as additional error information can always be put into thread local storage.

**Comment by est31** [comment]
I've added another variant to the error. Originally I wanted to add a trait object but seems that this is not possible as it would have to implement lots of traits that I can't all require as trait objects implementing multiple traits are not supported. So no payload it is.

**Comment by paulhowardarm** [comment]
That's great. Thank you very much for responding to this.
