### ISSUE TITLE
Support specifying keypairs yourself

### ISSUE THREAD

**Issue by est31** [est31/rcgen#7]
It'd be cool if you could specify the keypairs used for signing yourself.

**Comment by fzgregor** [comment]
Hi, I gave this a shot at https://github.com/fzgregor/rcgen/commit/82eea9f68f167c36ff6d5e6af078fef41d3b86c6

I'm not very satisfied with the PKCS8 key importing though. Maybe you have a better idea. Let me know what you think.

Also #8 would be nice to have. As the key comes from the outside and might be completely bogus.

**Comment by est31** [comment]
@fzgregor thanks, that's a great implementation. Feel free to file a PR so that I can review!

**Comment by est31** [comment]
> I'm not very satisfied with the PKCS8 key importing though. Maybe you have a better idea. Let me know what you think.

For the code itself, I'd prefer `let Ok(...) = { return ...}` because it avoids rightward drift. Otherwise we might want to do a `TryFrom` implementation instead of `From` but that doesn't have to be done in your PR, it could be done separately.

Your implementation checks each method and then decide based on that. For an initial implementation, this is more than okay. I don't think there is a better method other than parsing the ASN.1 ourselves which has its own set of issues.

**Comment by fzgregor** [comment]
> For the code itself, I'd prefer `let Ok(...) = { return ...}` because it avoids rightward drift.

Right! Did that. Thanks for the hint.

I opened a pull request #9

**Comment by tjpalmer** [comment]
Just stopping by to say that this is exactly what I was looking into myself at the moment, so thanks for being a few days ahead of me!

Basically, I just want to have a pre-existing generated ca key pair on disk and then use that to sign new certs. This would support that use case, right?

**Comment by est31** [comment]
@tjpalmer this PR will make it *possible* but not as easy as it could be, because you'll have to parse the certificate yourself and create the corresponding `CertificateParams` struct of the CA cert (yet beyond the key, the distinguished name, and the algorithm nothing is relevant). This involves parsing of the cert for which there are crates e.g. `x509-parser`. Maybe in the future this could be made easier but not sure if I want this crate to become a general x509 utility.

**Comment by fzgregor** [comment]
Hi @tjpalmer,
I have exactly the same use case as you. I have some code already that uses `x509-parser` to get the necessary information to generate a `CertificateParams` struct.
@est31 I'm thinking about a `From<(&[u8], `KeyPair`)>` for `CertificateParams` that uses `x509-parser` with a feature gate. WDYT, is that something you like `rcgen` to support?
IHMO, this is a pretty standard use case.

**Comment by est31** [comment]
@fzgregor okay then I guess I give in to the pressure from my users :). I was on the fence more or less.

> I'm thinking about a From<(&[u8], KeyPair)> for CertificateParams that uses x509-parser with a feature gate.

Yeah, it should be feature gated and marked off by default. The creation of self-signed certificates is possible without that feature, too. As for the API, instead of a From implementation, I'd like a function on `CertificateParams` instead returning `Self` that takes in two parameters: the private key as well as the DER encoded certificate. Plus points if you also add a pem implementation :).

**Comment by est31** [comment]
The feature of allowing users to specify keypairs themselves has been implemented by #9.
