### ISSUE TITLE
Can we create CSRs?

### ISSUE THREAD

**Issue by buehler** [est31/rcgen#78]
Hey there!

I'm currently playing around with your package. I try to create a CA that can receive a CSR and sign the CSR. While I saw that I cannot use RSA (because of ring as far as I understand), it seems that I cannot create a CSR in code as well, since I cannot extract the public key from a KeyPair.

Do you have any advice on how I can manage to create such a PKI, or am I bound to other languages such as go?

Nevertheless, nice work in this lib!

Regards

**Comment by mike-lloyd03** [comment]
I too am wondering this.

**Comment by mike-lloyd03** [comment]
@buehler I found this in the tests that gives some insight into how to sign a CSR:

https://github.com/est31/rcgen/blob/28a7562e48231c28c898beb86583cb7ac44a0c3f/tests/webpki.rs#L388-L408

It requires serializing the `Certificate` into der and then generating a `CertificateSigningRequest` from the der. Problem is, the `from_der()` function currently doesn't support any extensions except `Subject Alternative Name`. So the cert stemming from this operation won't recognize any extensions you apply (`extendedKeyUsage`, `not_before`, `not_after`). Making it unusable for server authentication.

```rust
pub fn from_der(csr: &[u8]) -> Result<Self, RcgenError>

Parse a certificate signing request from DER-encoded bytes

Currently, this only supports the Subject Alternative Name extension. On encountering other extensions, this function will return an error.
```

**Comment by buehler** [comment]
Hey @mike-lloyd03 
I found out that we can't :-)

So, I found a workaround with the openssl package in rust.

**Comment by est31** [comment]
Adding support for additional extensions shouldn't be hard. Mostly it's plumbing the data from the `x509-parser` crate to rcgen's internal format. PRs are welcome (especially those that add / extend tests)!

**Comment by buehler** [comment]
@mike-lloyd03  Happy to help then :-)

For the record, you find all code here: https://github.com/WirePact/k8s-pki

Step by step, you need to do the following parts. Keep in mind that you could split this to multiple applications (e.g. you have PKI like my project that handles the CA and a client that requests a certificate via CSR).

## Create a private RSA key
Since `rcgen` does not support RSA (because of "ring"), you can create an RSA private key with openssl as well.

```rust
pub fn create_new_key() -> Result<PKey<Private>, Box<dyn Error>> {
    let rsa = Rsa::generate(2048)?;
    let key = PKey::from_rsa(rsa)?;

    Ok(key)
}
```

## Create the CA cert
```rust
pub fn create_new_ca(serial_number: u32, key: &PKeyRef<Private>) -> Result<X509, Box<dyn Error>> {
    let mut name = X509Name::builder()?;
    name.append_entry_by_nid(Nid::COMMONNAME, "COMMON NAME HERE")?;
    name.append_entry_by_nid(Nid::ORGANIZATIONNAME, "YOUR ORG NAME")?;
    let name = name.build();

    let not_before = Asn1Time::days_from_now(0)?;
    let not_after = Asn1Time::days_from_now(365 * 5)?;

    let mut builder = X509::builder()?;
    builder.set_version(2)?;
    builder.set_subject_name(&name)?;
    builder.set_issuer_name(&name)?;
    builder.set_serial_number(
        Asn1Integer::from_bn(BigNum::from_u32(serial_number)?.as_ref())?.as_ref(),
    )?;
    builder.set_not_before(not_before.as_ref())?;
    builder.set_not_after(not_after.as_ref())?;
    builder.set_pubkey(key)?;
    builder.sign(key, MessageDigest::sha256())?;

    Ok(builder.build())
}
```

You can add various identifier object in the name builder as you may wish. Be sure to add "not before" and "not after", as well as the serial number.
The last steps set the public key to your created key and sign the CA with the private key.

## Create the CSR
```rust
let mut req_builder = X509Req::builder()?;
req_builder.set_pubkey(my_key.as_ref())?;
req_builder.set_version(2)?;
let mut name = X509Name::builder()?;
name.append_entry_by_nid(Nid::COMMONNAME, "FOOOBAR")?;
name.append_entry_by_nid(Nid::ORGANIZATIONNAME, "Whoami?")?;
let name = name.build();
req_builder.set_subject_name(name.as_ref())?;
req_builder.sign(my_key.as_ref(), MessageDigest::sha256())?;

let req = req_builder.build();
```

To build a CSR, you need the `X509Req::builder()` thing. You need to set the subject name and the public key and then sign the builder object with your private key.

This request can then be converted to `pem` or `der`.

## Sign CSR
On the receiving side, you take the (in this example) pem encoded CSR from the last step:
```rust
let csr = X509Req::from_pem(PEM CONTENT)?;
```

Now for the signing part: You need to create a builder that sets certain elements and then sign the whole thing with the private key of the CA.

```rust
async fn sign_csr(&self, request: X509Req) -> Result<X509, Box<dyn Error>> {
    let ca_cert = self.cert();
    let ca_key = self.key();
    let next_number = self.next_serial_number().await?;
    let not_before = Asn1Time::days_from_now(0)?;
    let not_after = Asn1Time::days_from_now(365 * 5)?;

    let mut builder = X509::builder()?;
    builder.set_version(request.version())?;
    builder.set_subject_name(request.subject_name())?;
    builder.set_pubkey(request.public_key()?.as_ref())?;
    builder.set_not_before(not_before.as_ref())?;
    builder.set_not_after(not_after.as_ref())?;

    match request.extensions() {
        Ok(extensions) => extensions
            .iter()
            .map(|ext| builder.append_extension2(ext))
            .collect::<Result<Vec<_>, _>>()
            .map(|_| ()),
        _ => Ok(()),
    }?;
    builder.set_issuer_name(ca_cert.subject_name())?;
    builder.set_serial_number(
        Asn1Integer::from_bn(BigNum::from_u32(next_number)?.as_ref())?.as_ref(),
    )?;
    builder.sign(ca_key.as_ref(), MessageDigest::sha256())?;

    info!(
        "Sign CSR for '{:?}' with serial number '{}'.",
        request.subject_name(),
        next_number
    );

    Ok(builder.build())
}
```

The steps are as follows:
- Fetch CA certificate
- Fetch CA private key
- Fetch next serial number
- Create notbefore/notafter (important)
- create builder
- set version of the CSR reqeust
- set subject name and public key from request
- set notbefore/notafter
- copy all extensions
- set issuer name to CA subject name
- set serial number
- sign builder with private key of the CA

After those steps, you have a valid signed certificate that you can return to your requester.
