### ISSUE TITLE
Raw bytes expected instead for RemoteKeyPair#public_key

### ISSUE THREAD

**Issue by nelson-ks** [est31/rcgen#83]
It is stated in the doc that the public_key should returned in DER format
https://docs.rs/rcgen/0.9.2/rcgen/trait.RemoteKeyPair.html#tymethod.public_key

However it should be the raw bytes of the public key as this is what provided from ring
https://docs.rs/rcgen/0.9.2/src/rcgen/lib.rs.html#1781
I can't find in the docs of thering library but here it says the output from ring is in raw format
https://docs.rs/rcgen/0.9.2/rcgen/struct.KeyPair.html#method.public_key_raw

**Comment by est31** [comment]
I guess this was an oversight of 261aded17b4979b0d56ca1dafade1889837d3eb3 ... It's good that I made the attempt to document the format at all though, as it shows that people are interested in it. PRs to fix welcome!

**Comment by nelson-ks** [comment]
Ah I see. 
I thought it expects some DER identifier when it mentions DER format.

I have make a PR. #84  Please feel free to comment.
And thank you for your work. It is very helpful

**Comment by est31** [comment]
Fixed by #84
