### ISSUE TITLE
Open to a formatting with rustfmt?

### ISSUE THREAD

**Issue by clangenb** [est31/rcgen#85]
Formatting with `cargo fmt` has been widely adopted by now. I was wondering if you were open to introduce formatting with rustfmt?

You could introduce a `.rustfmt.toml`, which almost maintains the current formatting config.

**Comment by est31** [comment]
Not at the moment, thank you. Last time I checked, rustfmt still mixes tabs and spaces, but I want this to have tabs only until the first non-whitespace character on each line, after which it should be spaces only.

**Comment by clangenb** [comment]
Oh, I see, I was not aware of this. Thanks for explaining!

And I double-checked: You are right, rustfmt still mixes tabs and spaces.

**Comment by cpu** [comment]
Is there any chance you might be willing to reconsider this decision? :angel: 

I don't want to start a heated debate but from the perspective of an outside contributor the current manual formatting is a challenge. Having to think about formatting adds a fair bit of cognitive overhead + review time that could be avoided entirely with `rustfmt`. 

Perhaps use of this crate has grown to the point where it makes sense to prioritize consistency with the broader Rust ecosystem to facilitate ease of outside contributions?

**Comment by est31** [comment]
Hmm yeah originally in most releases, most of the commits have come from me with a few commits from outside contributors. The 0.11.0 release was different though as most commits have come from contributors. Maybe I can write a small script that calls rustfmt internally that un-does the tab/space mixing...

**Comment by cpu** [comment]
Thanks for giving it some consideration.

> Maybe I can write a small script that calls rustfmt internally that un-does the tab/space mixing...

That sounds like an OK middle ground. Personally I'd probably just embrace `rustfmt` and its warts instead of having to maintain additional tooling but maybe I've got brain worms from too many years of universally applying `go fmt`.
