### ISSUE TITLE
Proposal: add `mkcert` to Cargo.toml keywords.

### ISSUE THREAD

**Issue by vi** [est31/rcgen#90]
This crate is hard to find on Crates.io, as it lacks categories and keywords.

I suggest to add them. Apart from obvious keywords like `certificate`, `tls`, `ca` and `X.509`, I suggest to also include `mkcert` keyword. It is a popular CLI tool that does some things that this library also does, so it may serve as a way to discover this library.

**Comment by est31** [comment]
Yeah I guess mkcert is pretty famous so adding it is a good idea. PRs welcome!
