### ISSUE TITLE
Incompatibility between 0.9.4 and 0.9.2

### ISSUE THREAD

**Issue by jkitman** [est31/rcgen#92]
I noticed that the following code was broken when upgrading to the latest patch version: `rcgen::IsCa::SelfSignedOnly`

Should this be a minor version release?

**Comment by est31** [comment]
Oh right good point, it should be 0.10.0 I'm yanking 0.9.4. Thanks for pointing this out.

**Comment by est31** [comment]
0.9.4 is yanked, I've [released 0.10.0](https://github.com/est31/rcgen/releases/tag/v0.10.0)
